- clean:
  - '~'
  - ~/.cargo
  - ~/.config

- create:
  - ~/.cache/mutt/headers
  - ~/.cache/mutt/messages
  - ~/.cache/mutt/messages
  - ~/.cargo
  - ~/.config/alacritty
  - ~/.config/fish
  - ~/.config/git
  - ~/.config/gsimplecal
  - ~/.config/helix
  - ~/.config/i3status
  - ~/.config/menus
  - ~/.config/neofetch
  - ~/.config/nixpkgs/overlays
  - ~/.config/nvim
  - ~/.config/polybar
  - ~/.config/src
  - ~/.config/sway
  - ~/.config/swaylock
  - ~/.config/swaynag
  - ~/.config/taffybar
  - ~/.config/xmobar
  - ~/.config/xonsh
  - ~/.elinks
  - ~/.gnupg
  - ~/.local/share
  - ~/.mutt
  - ~/.nixpkgs
  - ~/.rusty-tags
  - ~/.tmux/plugins
  - ~/.vim/autoload
  - ~/.xmonad
  - ~/src
  - ~/tmp

- link:
    ~/.bitcoin: '~/Library/Application Support/Bitcoin/'
    ~/.colordiffrc: etc/colordiffrc
    ~/.config/alacritty/alacritty.yaml: etc/alacritty.yaml
    ~/.config/alacritty/alacritty.yml: etc/alacritty.yml
    ~/.config/bpython: etc/bpython
    ~/.config/feh: etc/feh
    ~/.config/fish/completions: etc/fish-completions
    ~/.config/fish/config.fish: etc/config.fish
    ~/.config/fish/functions: etc/fish-functions
    ~/.config/git/config: etc/gitconfig
    ~/.config/gsimplecal/config: etc/gsimplecal
    ~/.config/helix/config.toml: etc/helix.toml
    ~/.config/i3status/config: etc/i3status.config
    ~/.config/nvim/init.vim: etc/nvim.vim
    ~/.config/polybar/config: etc/polybar
    ~/.config/src/config.yaml: etc/src.yaml
    ~/.config/sway/config: etc/sway.config
    ~/.config/swaylock/config: etc/swaylock.config
    ~/.config/swaynag/config: etc/swaynag.config
    ~/.config/taffybar/taffybar.hs: etc/taffybar.hs
    ~/.config/taffybar/taffybar.rc: etc/taffybar.rc
    ~/.config/user-dirs.dirs: etc/user-dirs.dirs
    ~/.config/xmobar/xmobarrc: etc/xmobarrc
    ~/.config/xonsh/config.json: etc/xonsh.json
    ~/.dotfiles: .
    ~/.elinks/elinks.conf: etc/elinks.conf
    ~/.fxfile: etc/fxfile
    ~/.gdbinit: etc/gdbinit
    ~/.gitignore.global: etc/gitignore.global
    ~/.gnupg/gpg-agent.conf: etc/gpg-agent.conf
    ~/.gnupg/gpg.conf: etc/gpg.conf
    ~/.hushlogin: etc/hushlogin
    ~/.inputrc: etc/inputrc
    ~/.lldbinit: etc/lldbinit
    ~/.mutt/muttrc: etc/muttrc
    ~/.nethackrc: etc/nethackrc
    ~/.nixpkgs/config.nix: etc/nixpkgs.nix
    ~/.plan: etc/plan
    ~/.project-root.yaml: etc/project-root.yaml
    ~/.project: etc/project
    ~/.ripgreprc: etc/ripgreprc
    ~/.rusty-tags/config.toml: etc/rusty-tags.toml
    ~/.sh.py: etc/sh.py
    ~/.skhdrc: etc/skhdrc
    ~/.spacemacs: etc/spacemacs
    ~/.tigrc: etc/tigrc
    ~/.tmux.conf: etc/tmux.conf
    ~/.tmux/plugins/tpm: submodules/tpm
    ~/.user.justfile: etc/user.justfile
    ~/.vim.py: etc/vim.py
    ~/.vim/autoload/plug.vim: submodules/vim-plug/plug.vim
    ~/.vim: etc/vim
    ~/.vimrc: etc/vimrc
    ~/.wallpaper: wallpaper/moebius-conversation.png
    ~/.wgetrc: etc/wgetrc
    ~/.xbindkeysrc: etc/xbindkeysrc
    ~/.xmonad/xmonad.hs: etc/xmonad.hs
    ~/.xonshrc: etc/xonshrc
    ~/.xresources: etc/xresources
    ~/.xscreensaver: etc/xscreensaver
    ~/.yabairc: etc/yabairc
    ~/.zlogout: etc/zlogout
    ~/.zsh: etc/zsh
    ~/.zshrc: etc/zshrc
    ~/bin: bin

- shell:
  - |
    OS_CONFIG=os/`uname | tr '[:upper:]' '[:lower:]'`/default.yaml
    if [[ -f $OS_CONFIG ]]; then
      ./submodules/dotbot/bin/dotbot -c $OS_CONFIG
    fi
  - |
    HOST_CONFIG=box/$HOST/default.yaml
    if [[ -f $HOST_CONFIG ]]; then
      ./submodules/dotbot/bin/dotbot -c $HOST_CONFIG
    fi
  - chmod 700 ~/.vim
  - chmod 700 ~/.gnupg
