set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'

unbind c-b
bind c-o send-prefix

set -g base-index 1
set -s default-terminal screen-256color
set -g display-time 1000
set -g focus-events on
set -g history-limit 50000
set -g message-style bg=default,fg=blue
set -g mode-keys vi
set -g mouse on
set -g pane-active-border-style fg=blue
set -g pane-base-index 1
set -g pane-border-style fg=colour242
set -g prefix c-o
set -g status-interval 1
set -g status-justify left
set -g status-keys emacs
set -g status-left "⎡#S⎤ "
set -g status-right "⎡#{?#{!=:#{battery_percentage},},⚛ #{battery_percentage} │ ,}☉ %a %-m.%d │ ♁ %l:%M %p⎤"
set -g status-style bg=default,fg=blue
set -g window-status-current-format "#I:#W#{?window_zoomed_flag,*,}"
set -g window-status-current-style bg=blue,fg=black
set -g window-status-format "#I:#W#{?window_zoomed_flag,*,}"
set -g window-status-separator " "
set -ga terminal-overrides ,alacritty:RGB
set -s escape-time 0

if \
  "sysctl -n machdep.cpu.brand_string | grep M1" \
  "set -g default-command \"arch -arm64 zsh\""

bind e select-layout even-horizontal
bind E select-layout even-vertical
bind s source ~/.tmux.conf \; display "Sourced!"
bind '"' split-window -c '#{pane_current_path}' -h
bind = split-window -c '#{pane_current_path}'
bind % choose-buffer
bind -r c-h select-window -t :-
bind -r c-l select-window -t :+
bind -r c-k swap-pane -U
bind -r c-j swap-pane -D
bind -r L resize-pane -R 5
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5

unbind -T copy-mode-vi Enter
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel cpy
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel cpy
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel cpy

set -g @IS_VIM \
  "ps -o state= -o comm= -t '#{pane_tty}' \
  | grep -iqE '^[^TXZ ]+ +(\\S+/)?g?(view|n?vim?x?)(diff)?$'"
bind -n M-h if "#{@IS_VIM}" "send M-h" "select-pane -L"
bind -n M-j if "#{@IS_VIM}" "send M-j" "select-pane -D"
bind -n M-k if "#{@IS_VIM}" "send M-k" "select-pane -U"
bind -n M-l if "#{@IS_VIM}" "send M-l" "select-pane -R"
bind -n 'M-\' if "#{@IS_VIM}" "send M-\\" "select-pane -l"
bind -T copy-mode-vi M-h select-pane -L
bind -T copy-mode-vi M-j select-pane -D
bind -T copy-mode-vi M-k select-pane -U
bind -T copy-mode-vi M-l select-pane -R
bind -T copy-mode-vi 'M-\' select-pane -l

bind -n M-H select-window -t :-
bind -n M-L select-window -t :+

run -b '~/.tmux/plugins/tpm/tpm'

bind -T root F12 {
  set prefix None
  set key-table off
  set status off
  if -F '#{pane_in_mode}' 'send -X cancel'
  refresh -S
}

bind -T off F12 {
  set -u prefix
  set -u key-table
  set -u status
  refresh -S
}
