import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12.0

[font.glyph_offset]
x = 0
y = 0

[font.bold]
family = "DejaVuSansM Nerd Font"
style = "Bold"

[font.italic]
family = "DejaVuSansM Nerd Font"
style = "Oblique"

[font.normal]
family = "DejaVuSansM Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
post_processing = true
regex = '''
(?x)
(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)
[^\u0000-\u001F\u007F-\u009F<>"\s{-}\^⟨⟩`]+
'''

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

 [[keyboard.bindings]]
 action = "ResetFontSize"
 key = "Key0"
 mods = "Command"

 [[keyboard.bindings]]
 action = "IncreaseFontSize"
 key = "Equals"
 mods = "Command"

 [[keyboard.bindings]]
 action = "DecreaseFontSize"
 key = "Minus"
 mods = "Command"

 [[keyboard.bindings]]
 action = "Paste"
 key = "V"
 mods = "Command"

 [[keyboard.bindings]]
 action = "Copy"
 key = "C"
 mods = "Command"

 [[keyboard.bindings]]
 action = "Quit"
 key = "Q"
 mods = "Command"

 [[keyboard.bindings]]
 action = "Quit"
 key = "W"
 mods = "Command"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["-i", "--login", "-c", "shell"]
program = "/opt/homebrew/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = true
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 199
lines = 59

[window.padding]
x = 2
y = 2
