#!/usr/bin/env bash

set -euxo pipefail

NAME=$1

c:() {
  if [[ ! -e ~/.cargo/bin/$2 ]]; then
    cargo install $1
  fi
}

sudo scutil --set ComputerName $NAME
sudo scutil --set LocalHostName $NAME
sudo scutil --set HostName $NAME

if [[ ! -e /opt/homebrew/bin/brew ]]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [[ ! -e ~/.ssh/id_ed25519.pub ]]; then
  ssh-keygen -t ed25519 -C $USER@`hostname`
  cat ~/.ssh/id_ed25519.pub | pbcopy
fi

brew bundle install --no-lock --file os/darwin/Brewfile

just bootstrap

if [[ ! -e ~/.vim/plugged ]]; then
  vim +PlugInstall
fi

if [[ ! -e ~/.cargo/bin/cargo ]]; then
  rustup-init
fi

c: cargo-limit cargo-lcheck
c: nvim-send nvim-send

if [[ ! -e ~/.cargo/bin/shell ]]; then
  cargo install --path pkg/shell
fi
