- link:
    ~/.config/alacritty/box.yaml: alacritty.yaml
    ~/Library/LaunchAgents/com.rodarmor.bitcoin-regtest.plist: com.rodarmor.bitcoin-regtest.plist
    ~/Library/LaunchAgents/com.rodarmor.bitcoin-signet.plist: com.rodarmor.bitcoin-signet.plist
    ~/Library/LaunchAgents/com.rodarmor.bitcoin-testnet.plist: com.rodarmor.bitcoin-testnet.plist
