#!/usr/bin/env bash

set -euxo pipefail

if [[ `hostname` != finnix ]]; then
  exit 1
fi

grep Finnix /etc/issue || exit 1

swapoff --all
umount /mnt || true
wipefs --all /dev/sda
sgdisk --zap-all /dev/sda

parted --script /dev/sda mklabel gpt
parted --script /dev/sda mkpart bios 1MiB 2MiB
parted --script /dev/sda set 1 bios_grub on
parted --script /dev/sda mkpart root 2MiB 100%

partprobe /dev/sda
udevadm settle

mkfs.ext4 -L root /dev/sda2

mount LABEL=root /mnt

mkdir --parents /etc/nix
echo 'build-users-group =' > /etc/nix/nix.conf

if [[ ! -f /root/.nix-profile/etc/profile.d/nix.sh ]]; then
  sh <(curl -L https://nixos.org/nix/install) --no-daemon
fi

. /root/.nix-profile/etc/profile.d/nix.sh

nix-channel --add https://nixos.org/channels/nixos-unstable nixos
nix-channel --update

nix-env --install -E '_: with import <nixpkgs/nixos> { configuration = {}; }; with config.system.build; [ nixos-generate-config nixos-install ]'

nixos-generate-config --root /mnt

cp configuration.nix /mnt/etc/nixos/configuration.nix

nixos-install --no-root-passwd --root /mnt
